name: Build MinGW-w64 Toolchains

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build MinGW-w64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [i686, x86_64]
        msvcrt: [msvcrt, ucrt]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bison flex

    - name: Build MinGW-w64 toolchain
      run: |
        chmod +x mingw-w64-build
        ./mingw-w64-build -j$(nproc) --msvcrt ${{ matrix.msvcrt }} ${{ matrix.target }}

    - name: Create tarball
      run: |
        TOOLCHAIN_DIR="$HOME/toolchains"
        VERSION=$(./mingw-w64-build -v | cut -d' ' -f2)
        GCC_VERSION=$(echo "$VERSION" | cut -d'.' -f1-2)
        MINGW_VERSION=$(grep 'MINGW_W64_VER=' mingw-w64-build | cut -d'"' -f2)
        TARBALL_NAME="mingw-w64-${MINGW_VERSION}-${{ matrix.msvcrt }}-gcc-${GCC_VERSION}-${{ matrix.target }}-linux"
        
        cd "$TOOLCHAIN_DIR"
        tar czf "$GITHUB_WORKSPACE/${TARBALL_NAME}.tar.gz" mingw-w64-*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mingw-w64-${{ matrix.target }}-${{ matrix.msvcrt }}
        path: mingw-w64-*.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: mingw-w64-*/mingw-w64-*.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
